In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])

In [4]:
a2 = np.array([[1,2,3],[4,5,6]])

In [5]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]], [[10,11,12],[13,14,15],[16,17,18]]])

In [6]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [8]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [10]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [11]:
import pandas as pd
df = pd.DataFrame(a2)

In [12]:
df

0  1  2
0  1  2  3
1  4  5  6

In [13]:
ones = np.ones((10,2))

In [14]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
zeros = np.zeros((7,2,3))

In [16]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
range_array = np.arange(0,100,3)

In [20]:
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [21]:
random_array = np.random.randint(10, size=(7,2))

In [22]:
random_array

array([[7, 9],
       [5, 6],
       [9, 4],
       [4, 9],
       [2, 9],
       [1, 9],
       [2, 5]])

In [23]:
np.random.random((3,5))

array([[0.32455083, 0.42781136, 0.585998  , 0.54890025, 0.78406033],
       [0.26470164, 0.33759805, 0.95763025, 0.9025727 , 0.36351893],
       [0.35219592, 0.67929727, 0.58001861, 0.34958555, 0.89984902]])

In [24]:
np.random.seed(42)

In [25]:
np.random.randint(10, size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [26]:
array = np.random.randint(10, size=(3,7))

In [27]:
np.unique(array)

array([0, 1, 2, 3, 4, 6, 8, 9])

In [28]:
array[0]

array([8, 0, 9, 2, 6, 3, 8])

In [29]:
array[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [30]:
array[:2, :2]

array([[8, 0],
       [2, 4]])

In [31]:
a4 = np.random.randint(10,size=(3,5))

In [32]:
ones = np.ones((3,5))

In [33]:
a4 + ones

array([[ 5.,  2.,  4.,  7.,  8.],
       [ 3.,  1.,  4.,  2.,  8.],
       [ 4.,  2.,  6.,  6., 10.]])

In [34]:
ones = np.ones((5,3))

In [35]:
a4 + ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [36]:
ones = np.ones((3,5))

In [37]:
a4 - ones

array([[ 3.,  0.,  2.,  5.,  6.],
       [ 1., -1.,  2.,  0.,  6.],
       [ 2.,  0.,  4.,  4.,  8.]])

In [38]:
a4 * ones

array([[4., 1., 3., 6., 7.],
       [2., 0., 3., 1., 7.],
       [3., 1., 5., 5., 9.]])

In [39]:
a4 ** 2

array([[16,  1,  9, 36, 49],
       [ 4,  0,  9,  1, 49],
       [ 9,  1, 25, 25, 81]])

In [40]:
np.square(a4)

array([[16,  1,  9, 36, 49],
       [ 4,  0,  9,  1, 49],
       [ 9,  1, 25, 25, 81]])

In [41]:
np.mean(a4)

3.8

In [42]:
np.max(a4)

9

In [43]:
np.min(a4)

0

In [44]:
np.var(a4)

6.5600000000000005

In [45]:
a4.reshape(3,5,1)

array([[[4],
        [1],
        [3],
        [6],
        [7]],

       [[2],
        [0],
        [3],
        [1],
        [7]],

       [[3],
        [1],
        [5],
        [5],
        [9]]])

In [46]:
a4.T

array([[4, 2, 3],
       [1, 0, 1],
       [3, 3, 5],
       [6, 1, 5],
       [7, 7, 9]])

In [47]:
mat1 = np.random.randint(10, size=(3,3))

In [48]:
mat2 = np.random.randint(10, size=(3,2))

In [49]:
np.dot(mat1, mat2)

array([[ 48,  33],
       [112, 127],
       [ 76,  70]])

In [50]:
mat3 = np.random.randint(10, size=(4,3))

In [51]:
mat4 = np.random.randint(10, size=(4,3))

In [52]:
np.dot(mat3, mat4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [53]:
np.dot(mat3.T, mat4)

array([[128, 153, 146],
       [135, 140, 167],
       [ 28,  68,  56]])

In [54]:
mat5 = np.random.randint(10, size=(4,2))

In [55]:
mat6 = np.random.randint(10, size=(4,2))

In [56]:
mat5 > mat6

array([[False, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

In [57]:
mat5 > 7 

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [58]:
mat5 == mat6

array([[ True, False],
       [False, False],
       [False, False],
       [False, False]])

In [59]:
np.sort(mat5)

array([[1, 7],
       [0, 6],
       [6, 7],
       [2, 4]])

In [60]:
np.argsort(mat6)

array([[1, 0],
       [1, 0],
       [0, 1],
       [1, 0]])

In [61]:
np.argmax(mat5)

0

In [62]:
np.argmin(mat6)

3

In [67]:
np.argmax(mat6, axis=0)

array([0, 0])

In [68]:
np.random.randn(3,5)

array([[-0.93376284,  0.78420819, -0.61487576,  0.33289244, -1.38071702],
       [-0.28080629, -0.05981726,  0.96117377,  1.79428084,  0.58068954],
       [ 0.29765045, -1.02811577, -1.41859646,  0.19033698,  0.13575383]])

In [71]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])